module.exports = [
  "As pessoas só te incentivam para rir do seu fracasso.",
  "Seus sonhos nunca se realizarão.",
  "Ele só te comeu por falta de opção.",
  "Ela não é dificil, você que é feio.",
  "Ela saiu com você para comer de graça.",
  "As vezes a vida te levanta só pra você cair de novo.",
  "Você é um erro.",
  "Para de bater punheta pra desenho.",
  "Pra ser inútil você tem que melhorar muito.",
  "Sua sombra só te segue porque é obrigada.",
  "Azar no amor, azar no dinheiro e sorte no azar.",
  "Ela pediu um tempo porque queria dar para outro.",
  "A tendência é piorar.",
  "As pessoas só te respondem para você parar de encher o saco.",
  "Ela só te usou para fazer ciúme no ex.",
  "Ta todo mundo transando menos você.",
  "Você nunca vai conseguir.",
  "Calma, o pior ainda está por vir.",
  "Vai dar merda.",
  "Mais um dia que passa e tua insignificância prevalece.",
  "A inteligência artificial não é páreo para a estupidez natural!",
  "Finalmente ela olhou pra você. E te achou feio.",
  "Ele ainda se lembra de você. Com raiva!",
  "Não desanime com a derrota de hoje. Amanhã tem outra.",
  "Jesus só te ama por quê não convive com você",
  "Que merda é essa na minha cama? Ah... Sou só eu!",
  "Seu primo mais novo tá ganhando bem mais que você",
  "A vida é bela, mas você não!",
  "Tente ser feliz sem seus remédios",
  "O caminho é longo, mas a derrota é certa",
  "Nunca foi azar, sempre foi incompetência",
  "O não você já tem, busque a humilhação",
  "Lute como nunca, perca como sempre",
  "É sobre isso e tá tudo uma bosta",
  "Grandes derrotas exigem dedicação",
  "Calma, tudo vai piorar",
  "Acorda, o fracasso te espera",
  "Não há nada tão ruim que não possa piorar",
  "Tudo passa, nem que seja por cima de você"
];